### PR TITLE
refactor(refs T29004): re-add label tests

### PR DESCRIPTION
**Pull request by hwiem**
Ticket: https://yaits.demos-deutschland.de/T29004

- the label tests (that were disabled after refactoring the label props to be a single object) are fixed and enabled again
- some more tests that were disabled in DpInput.spec.js for unknown reasons are enabled again as well

### How to test

Run the tests, there should be no error

### CODE REVIEW

**Review by salisdemos — APPROVED** [review]
Thank You!

**Review by spiess-demos — COMMENTED** [review]
Why do we have to run the label tests in all other component tests, too? isn't it sufficient to test the label component for itself?

**Comment by hwiem** [comment]
> Why do we have to run the label tests in all other component tests, too? isn't it sufficient to test the label component for itself?

That's a very good question. By running them in other components we ensure that the props are passed properly from the outer component to DpLabel, but maybe that's not really the purpose of unit tests?

**Comment by spiess-demos** [comment]
> By running them in other components we ensure that the props are passed properly from the outer component to DpLabel, but maybe that's not really the purpose of unit tests?

As `runLabelTests` sets the props by itself, this is not exactly true. Testing child components in a component test looks (at least a little bit) like testing the implementation. To ensure that each form component has a working label implementation we could change `runLabelTests` so that it takes the props in question (`text`, `hint`, `required` and so on) as a second param, and then expexts the rendered html to contain those values within their expected html nodes.

**Comment by hwiem** [comment]
> > By running them in other components we ensure that the props are passed properly from the outer component to DpLabel, but maybe that's not really the purpose of unit tests?
> 
> As `runLabelTests` sets the props by itself, this is not exactly true. Testing child components in a component test looks (at least a little bit) like testing the implementation. To ensure that each form component has a working label implementation we could change `runLabelTests` so that it takes the props in question (`text`, `hint`, `required` and so on) as a second param, and then expexts the rendered html to contain those values within their expected html nodes.

I'm not sure I understand your concern. Why is it better to pass the props as a parameter?

**Comment by spiess-demos** [comment]
> I'm not sure I understand your concern. Why is it better to pass the props as a parameter?

Thanks for clarifying the `runLabelTests` approach in an 1:1. I simply did not look close enough, the test already does what i thought it should do.

**Review by spiess-demos — APPROVED** [review]
lgtm

**Pull request merged**
