### PR TITLE
refactor(refs T30969): move components to components root, pt. III

### PR DESCRIPTION
**Pull request by hwiem**
Ticket: https://yaits.demos-deutschland.de/T30969

Moves
- DpTreeList + related components
- DpDataTable + related components
- DpStickyElement

from `/components/core` to `/components`

### Tasks
- [x] revert moving DpSwitcher (should be removed entirely and replaced by DpToggle)
- [x] revert moving DpChangeStateAtDate (should be moved to demosplan-core)

### CODE REVIEW

**Review by spiess-demos — COMMENTED** [review]
DpChangeStateAtDate is a very specific component, i don't know if we want it to be part of demosplan-ui, at least with that name...

**Comment by hwiem** [comment]
> DpChangeStateAtDate is a very specific component, i don't know if we want it to be part of demosplan-ui, at least with that name...

I also had doubts about keeping it, so maybe we should just remove it?

**Comment by hwiem** [comment]
> DpSwitcher is used only one time, in the (deprecated) fragments view. The generic component is DpToggle here. Or do you think we want DpSwitcher as a separate component?

I guess we'll have to adjust DpToggle a bit? But then we should replace/remove DpSwitcher, thanks for pointing it out!

**Comment by spiess-demos** [comment]
> I guess we'll have to adjust DpToggle a bit? But then we should replace/remove DpSwitcher, thanks for pointing it out!

Which adjustments do you see here?

**Comment by hwiem** [comment]
> > I guess we'll have to adjust DpToggle a bit? But then we should replace/remove DpSwitcher, thanks for pointing it out!
> 
> Which adjustments do you see here?

I think DpToggle cannot handle labels (like 'fragment' and 'statement')?

**Comment by spiess-demos** [comment]
> I think DpToggle cannot handle labels (like 'fragment' and 'statement')?

I see... i did not think of DpToggle as a replacement for the actual implementation of DpSwitcher... DpSwitcher is just a very special UX solution in that place.

However maybe you're right and we can enhance DpToggle to have labels inside...

**Comment by hwiem** [comment]
> > I think DpToggle cannot handle labels (like 'fragment' and 'statement')?
> 
> I see... i did not think of DpToggle as a replacement for the actual implementation of DpSwitcher... DpSwitcher is just a very special UX solution in that place.
> 
> However maybe you're right and we can enhance DpToggle to have labels inside...

I think it's a good idea to try to reduce the toggle patterns we use, it's mostly that I don't have a good idea how to implement it for the DpSwitcher use case, but we can also discuss it later. For now I'd revert moving DpSwitcher?

**Review by spiess-demos — APPROVED** [review]
lgtm! code review only.

**Pull request merged**
