### PR TITLE
chore: Use Barrel Export to simplify index.js

### PR DESCRIPTION
**Pull request by salisdemos**
Instead of importing and exporting every Item explicitly, we can simply use a so called barrel export.

### CODE REVIEW

**Review by gruenbergerdemos — APPROVED** [review]
nice, lgtm!

**Review by hwiem — APPROVED** [review]
Nice, thanks!

**Review by spiess-demos — COMMENTED** [review]
Does this work in all circumstances? those are: tests, addons, storybook.

Before, we exposed modules via one huge **default** export (object). Now we forward the index files inside the directories that are barrel exported, instead. Those are named exports instead of default exports.

I do not know if this has a negative impact at all, just want to make sure that nothing is overlooked here. I also like the cleanliness here for sure.

**Comment by salisdemos** [comment]
> Does this work in all circumstances? those are: tests, addons, storybook.
> 
> Before, we exposed modules via one huge **default** export (object). Now we forward the index files inside the directories that are barrel exported, instead. Those are named exports instead of default exports.
> 
> I do not know if this has a negative impact at all, just want to make sure that nothing is overlooked here. I also like the cleanliness here for sure.

As far as I can see, Its all fine. Storybook still works. Tests pass. tested it in demosplan-core. Couldn't find anything that its not treeshakeable.... And if we find something, we still can revert it

**Review by spiess-demos — APPROVED** [review]
lgtm! code review only.

**Pull request merged**
