### PR TITLE
Fix(T34571): place tooltip in the foreground

### PR DESCRIPTION
**Pull request by sakutademos**
**Ticket:** https://yaits.demos-deutschland.de/T34571

**Description:** There are cases when tooltips are in the modal windows and have a smaller z-index than the modal.

- added a method that checks the z-index of the parent element and appends `zIndex + 1` to the style of the tooltip

### CODE REVIEW

**Review by spiess-demos — CHANGES_REQUESTED** [review]
This implementation would stack the tooltip always on top of everything else. This may be the desired behavior most of the time, but in cases where elements with higher hierarchy partly overlap a tooltip, the trigger element would then be stacked below the overlapping element (eg. a sidebar) but the tooltip would appear above.

I suggest to use a solution [based on this implementation](https://github.com/demos-europe/demosplan-core/blob/22e6a44496bd491cab280d8578bc83b3f33a164d/client/js/components/map/map/DpOlMapEditFeature.vue#L210-L217) but instead of setting a utility class we could just set a style attribute for the z-index that equals the z-index of the trigger element plus 1. This way we ensure that tooltips are always displayed above their respective trigger elements but below other elements of higher hierarchy.
As this implementation needs access to the trigger element, it needs to be implemented within the `initTooltip` and `showTooltip` methods of the Tooltip directive.

**Comment by sakutademos** [comment]
> This implementation would stack the tooltip always on top of everything else. This may be the desired behavior most of the time, but in cases where elements with higher hierarchy partly overlap a tooltip, the trigger element would then be stacked below the overlapping element (eg. a sidebar) but the tooltip would appear above.
> 
> I suggest to use a solution [based on this implementation](https://github.com/demos-europe/demosplan-core/blob/22e6a44496bd491cab280d8578bc83b3f33a164d/client/js/components/map/map/DpOlMapEditFeature.vue#L210-L217) but instead of setting a utility class we could just set a style attribute for the z-index that equals the z-index of the trigger element plus 1. This way we ensure that tooltips are always displayed above their respective trigger elements but below other elements of higher hierarchy. As this implementation needs access to the trigger element, it needs to be implemented within the `initTooltip` and `showTooltip` methods of the Tooltip directive.

Refactored it [here]( https://github.com/demos-europe/demosplan-ui/pull/523/commits/8f170bc1f696020c5827eda9fa144a18c4ed7a36). Did you mean this?

**Review by spiess-demos — APPROVED** [review]
Lgtm (code review only).

Non-blocking nitpick: one could argue if this is to be listed within "Added" (as per the added convenience of not having to manually define different z-index classes anymore) or within "Changed" (because of the changed behavior of the Tooltip directive).

**Comment by spiess-demos** [comment]
> > This implementation would stack the tooltip always on top of everything else. This may be the desired behavior most of the time, but in cases where elements with higher hierarchy partly overlap a tooltip, the trigger element would then be stacked below the overlapping element (eg. a sidebar) but the tooltip would appear above.
> > I suggest to use a solution [based on this implementation](https://github.com/demos-europe/demosplan-core/blob/22e6a44496bd491cab280d8578bc83b3f33a164d/client/js/components/map/map/DpOlMapEditFeature.vue#L210-L217) but instead of setting a utility class we could just set a style attribute for the z-index that equals the z-index of the trigger element plus 1. This way we ensure that tooltips are always displayed above their respective trigger elements but below other elements of higher hierarchy. As this implementation needs access to the trigger element, it needs to be implemented within the `initTooltip` and `showTooltip` methods of the Tooltip directive.
> 
> Refactored it [here](https://github.com/demos-europe/demosplan-ui/pull/523/commits/8f170bc1f696020c5827eda9fa144a18c4ed7a36). Did you mean this?

Exactly. Thanks for taking this on!

**Pull request merged**
