### PR TITLE
chore: Migrate from yarn1.22.22 to yarn4.2.2

### PR DESCRIPTION
**Pull request by salisdemos**
To use yarn4 we have to externalize some prosemirror dependencies. They are very picky if the get loaded twice for whatever reason.

### CODE REVIEW

**Review by spiess-demos — COMMENTED** [review]
as i'm stumbling across this in another project right this moment: why are we using prosemirror on its own anyway? `@tiptap/pm` [seems to exist for this reason](https://tiptap.dev/docs/editor/core-concepts/prosemirror): to enable prosemirror usage in parallel with tiptap, without version conflicts.

**Review by hwiem — COMMENTED** [review]
When running `yarn build`, I get this error:

```
error This project's package.json defines "packageManager": "yarn@4.2.2". However the current global version of Yarn is 1.22.22.

Presence of the "packageManager" field indicates that the project is meant to be used with Corepack, a tool included by default with all official Node.js distributions starting from 16.9 and 14.19.
Corepack must currently be enabled by running corepack enable in your terminal. For more information, check out https://yarnpkg.com/corepack.
```
I don't know if this is a local problem...?

**Comment by salisdemos** [comment]
> When running `yarn build`, I get this error:
> 
> ```
> error This project's package.json defines "packageManager": "yarn@4.2.2". However the current global version of Yarn is 1.22.22.
> 
> Presence of the "packageManager" field indicates that the project is meant to be used with Corepack, a tool included by default with all official Node.js distributions starting from 16.9 and 14.19.
> Corepack must currently be enabled by running corepack enable in your terminal. For more information, check out https://yarnpkg.com/corepack.
> ```
> 
> I don't know if this is a local problem...?

If You havent yarn 4.2.2 installed locally, You will get this error. 
If You have corepack installed locally,
```
npm install -g corepack
```
 you can easily switch the versions for yarn,
 ```
 corepack use yarn@4.2.2

 ```

**Comment by salisdemos** [comment]
> as i'm stumbling across this in another project right this moment: why are we using prosemirror on its own anyway? `@tiptap/pm` [seems to exist for this reason](https://tiptap.dev/docs/editor/core-concepts/prosemirror): to enable prosemirror usage in parallel with tiptap, without version conflicts.

I tried that solution too. It turns out, that it doesn't work - for whatever reason. I can imagine, that the specific module has to be externalized.

**Review by spiess-demos — COMMENTED** [review]
isn't this PR outdated as of the release of v0.4.0?

**Review by spiess-demos — APPROVED** [review]
lgtm (code review).
does this need any further treatment of CI/CD pipelines or deploy commands?

**Pull request merged**
